# pull official base image
FROM node:20.3.1-alpine

# create project directory
WORKDIR /app

# copy package
COPY . .

# install dependencies
RUN npm install

# assign permission users
RUN chmod 755 node_modules/

EXPOSE 4200 49153

# run project
CMD [ "npm", "start" ]
