FROM mcr.microsoft.com/mssql/server:2022-latest

# Configuración de variables de entorno
ENV SA_PASSWORD=MaxiTransfers2023
ENV ACCEPT_EULA=Y
ENV MSSQL_DB=maxitransfers

COPY ./ .

# Establecer el puerto
EXPOSE 1433

ENTRYPOINT [ "/bin/bash", "entrypoint.sh" ]