FROM mcr.microsoft.com/mssql/server:2022-latest

ENV SA_PASSWORD=MaxiTransfers2023
ENV ACCEPT_EULA=Y
ENV MSSQL_DB=maxitransfers

COPY . .

EXPOSE 1433

ENTRYPOINT [ "sh", "entrypoint.sh" ]
CMD [ "/opt/mssql/bin/sqlservr" ]